### ISSUE TITLE
Difference in Real Time Plot 

### ISSUE THREAD

**Issue by rajibshibly** [ropensci/tidyhydat#100]
Using the tidyhydat package realtime_plot option, I plotted for station 02ZM016 and obtained the following:
![image001](https://user-images.githubusercontent.com/39829190/40838849-77b1df14-657a-11e8-9f0d-06b78a2e237c.jpg)
But when I used the same station from the website (https://wateroffice.ec.gc.ca/report/real_time_e.html?mode=Graph&type=&startDate=2018-04-29&endDate=2018-05-29&stn=02ZM016&dataType=Real-Time)

The following plot came up. Can you explain the differences why it produced two different plot for the same time period.
![image002](https://user-images.githubusercontent.com/39829190/40838876-8a4405bc-657a-11e8-8146-300fb60a12c9.jpg)

**Comment by boshek** [comment]
This has to do with the axes scales and slight difference in the time period being analyzed. I imagine you might have captured the water office plot slightly before you grabbed the plot from `realtime_plot` coupled with the way ECCC updates their data sources may be contributing to the differences between the max date in each figure. But these are the same data and one is just viewing a different time windows at different scales. Also note how the double y-axes are possibly confusing the issue here.
