### ISSUE TITLE
Error with swith_lang

### ISSUE THREAD

**Issue by WatershedFlow** [ropensci/tidyhydat#130]
``` r
library(tidyhydat)

WoodR=hy_daily_flows(station_number = "05JA002", 
               start_date = "2016-03-01", end_date = "2016-05-31")
#> Error in switch_lang(call, inlined = , namespaced = , recursive = eval_bare(call, : could not find function "switch_lang"
```

<sup>Created on 2019-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by boshek** [comment]
👋  @WatershedFlow. Thanks for the bug report. Can you please post the result of `sessionInfo()`? I am unable to reproduce this. Seems likely that this is a package version issue (probably dplyr). However it would be helpful to know which version of dplyr you are using so that I ensure tidyhydat requires that version or above.

**Comment by WatershedFlow** [comment]
Sam,

I have fixed. it is because of dplyr. I installed it, then, it is fine.

Kangsheng

**Comment by boshek** [comment]
@WatershedFlow Did you happen to notice which version of dplyr you were using prior to updating?

**Comment by WatershedFlow** [comment]
Sam,
I do not know. What I know is that I did not use dbplyr before last week,
but tidyhydat worked fine. Then it did not work last week. I did some
search with "switch_lang" and someone pointed out that this kind of error
might be related with dbplyr, as you also mentioned. then the problem
fixed. Therefore, solution is to install dbplyr and other associated
packages.

Kangsheng
