### ISSUE TITLE
plans for update of HYDAT database?

### ISSUE THREAD

**Issue by sebdalgarno** [ropensci/tidyhydat#76]
First, thanks for your work on the package! it is very easy to use.

I was hoping to run some analysis using 2017 discharge data.
However, as you can see:
```
> hy_stations() %>%
+   # filter(STATION_NUMBER %in% c("08NN002", "08NN003", "08NN026")) %>%
+   pull(STATION_NUMBER) %>%
+   hy_daily_flows(start_date = "2017-01-01", end_date = "2017-12-31") %>%
+   pull(STATION_NUMBER) %>%
+   unique
All station successfully retrieved
More than 10 stations from the initial query were not returned. Ensure realtime and active status are correctly specified.
[1] "08HD032"
> 
```
 only one station in BC has any data for 2017. Any plans to update the database in the near future? I require data for 3 stations, all of which only have data up to 2014.

**Comment by boshek** [comment]
@sebdalgarno  - HYDAT, the database, is updated quarterly by Environment and Climate Change Change. However there is considerable lag between the collection of data and its entry in HYDAT primarily because the data has to be graded and validated prior to that. You can, however, use realtime_dd() to gather more recent data. The constraint here is that that data only stretches back 30 days. Right now those are the data sources that we have to work with.

**Comment by sebdalgarno** [comment]
Thanks for the explanation. It might be useful to clarify in the vignette that `realtime_dd()` gets data for the most recent 30 days.
